# アクション名
name: jest

# タイミングを指定
on:
  push:
    branches: [ first-action ]

jobs:
  jest:
    name: jest
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: npm i
      - name: run jest
        run: npm run test
