name: CI

on:
  push:
    branches: [ first-action ]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
      with:
        ref: first-action
    - name: Run a one-line script
      run: echo Hello, world!
